import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('products').del();

  // Get user IDs for reference
  const users = await knex('users').select('id', 'email');
  const productMasters = await knex('product_master').select('id', 'name');

  // Find specific users and product masters
  const budiUser = users.find(u => u.email === 'pakbudi@warungmaju.com');
  const mayaUser = users.find(u => u.email === 'ibumaya@tokoindah.com');
  const jokoUser = users.find(u => u.email === 'pakjoko@warungsejahtera.com');
  const sariUser = users.find(u => u.email === 'sari@minimarketmaju.com');
  const agusUser = users.find(u => u.email === 'pakagus@warungmakmur.com');

  const indomieGoreng = productMasters.find(p => p.name === 'Indomie Goreng');
  const indomieKuah = productMasters.find(p => p.name === 'Indomie Kuah Ayam Bawang');
  const mieSedap = productMasters.find(p => p.name === 'Mie Sedap Goreng');
  const rokokSampoerna = productMasters.find(p => p.name === 'Rokok Sampoerna Mild 16');
  const rokokDjarum = productMasters.find(p => p.name === 'Rokok Djarum Super 12');
  const aqua = productMasters.find(p => p.name === 'Aqua 600ml');
  const cocaCola = productMasters.find(p => p.name === 'Coca Cola 330ml');
  const sprite = productMasters.find(p => p.name === 'Sprite 330ml');
  const beras = productMasters.find(p => p.name === 'Beras Premium 5kg');
  const gula = productMasters.find(p => p.name === 'Gula Pasir 1kg');
  const minyak = productMasters.find(p => p.name === 'Minyak Goreng 2L');
  const kecap = productMasters.find(p => p.name === 'Kecap Manis 600ml');
  const sambal = productMasters.find(p => p.name === 'Sambal ABC 340ml');
  const telur = productMasters.find(p => p.name === 'Telur Ayam 1kg');
  const rokokMarlboro = productMasters.find(p => p.name === 'Rokok Marlboro Red 20');
  const pepsodent = productMasters.find(p => p.name === 'Pepsodent 190g');
  const rinso = productMasters.find(p => p.name === 'Rinso 800g');
  const roma = productMasters.find(p => p.name === 'Biskuit Roma 135g');
  const chitato = productMasters.find(p => p.name === 'Chitato 85g');
  const kopi = productMasters.find(p => p.name === 'Kopi Kapal Api 200g');

  // Inserts seed entries
  await knex('products').insert([
    // Budi's Warung Maju products
    {
      user_id: budiUser.id,
      product_master_id: indomieGoreng.id,
      name: 'Indomie Goreng',
      sku: 'BUDI-INDG-001',
      barcode: '8998866100012',
      description: 'Mie instan goreng rasa ayam bawang',
      unit: 'pcs',
      cost_price: 2800,
      selling_price: 3500,
      current_stock: 45,
      minimum_stock: 10,
      is_active: true,
      search_tags: ['indomie', 'goreng', 'mie', 'instan'],
      created_at: new Date('2024-01-15'),
      updated_at: new Date('2024-01-15'),
    },
    {
      user_id: budiUser.id,
      product_master_id: rokokSampoerna.id,
      name: 'Rokok Sampoerna Mild 16',
      sku: 'BUDI-SAMM-001',
      barcode: '8998866100074',
      description: 'Rokok filter mild 16 batang',
      unit: 'pack',
      cost_price: 22000,
      selling_price: 25000,
      current_stock: 12,
      minimum_stock: 5,
      is_active: true,
      search_tags: ['rokok', 'sampoerna', 'mild'],
      created_at: new Date('2024-01-15'),
      updated_at: new Date('2024-01-15'),
    },
    {
      user_id: budiUser.id,
      product_master_id: aqua.id,
      name: 'Aqua 600ml',
      sku: 'BUDI-AQUA-001',
      barcode: '8998866100098',
      description: 'Air mineral dalam botol 600ml',
      unit: 'botol',
      cost_price: 2500,
      selling_price: 3000,
      current_stock: 60,
      minimum_stock: 20,
      is_active: true,
      search_tags: ['aqua', 'air', 'mineral'],
      created_at: new Date('2024-01-15'),
      updated_at: new Date('2024-01-15'),
    },
    {
      user_id: budiUser.id,
      product_master_id: cocaCola.id,
      name: 'Coca Cola 330ml',
      sku: 'BUDI-COCA-001',
      barcode: '8998866100104',
      description: 'Minuman soda Coca Cola 330ml',
      unit: 'kaleng',
      cost_price: 6500,
      selling_price: 8000,
      current_stock: 25,
      minimum_stock: 10,
      is_active: true,
      search_tags: ['coca cola', 'cola', 'soda'],
      created_at: new Date('2024-01-15'),
      updated_at: new Date('2024-01-15'),
    },

    // Maya's Toko Indah products
    {
      user_id: mayaUser.id,
      product_master_id: indomieKuah.id,
      name: 'Indomie Kuah Ayam Bawang',
      sku: 'MAYA-INDK-001',
      barcode: '8998866100036',
      description: 'Mie instan kuah rasa ayam bawang',
      unit: 'pcs',
      cost_price: 2500,
      selling_price: 3000,
      current_stock: 30,
      minimum_stock: 8,
      is_active: true,
      search_tags: ['indomie', 'kuah', 'ayam', 'bawang'],
      created_at: new Date('2024-02-01'),
      updated_at: new Date('2024-02-01'),
    },
    {
      user_id: mayaUser.id,
      product_master_id: rokokDjarum.id,
      name: 'Rokok Djarum Super 12',
      sku: 'MAYA-DJAR-001',
      barcode: '8998866100081',
      description: 'Rokok kretek super 12 batang',
      unit: 'pack',
      cost_price: 19000,
      selling_price: 22000,
      current_stock: 8,
      minimum_stock: 3,
      is_active: true,
      search_tags: ['rokok', 'djarum', 'super', 'kretek'],
      created_at: new Date('2024-02-01'),
      updated_at: new Date('2024-02-01'),
    },
    {
      user_id: mayaUser.id,
      product_master_id: beras.id,
      name: 'Beras Premium 5kg',
      sku: 'MAYA-BERAS-001',
      barcode: '8998866100128',
      description: 'Beras premium putih 5kg',
      unit: 'karung',
      cost_price: 58000,
      selling_price: 65000,
      current_stock: 5,
      minimum_stock: 2,
      is_active: true,
      search_tags: ['beras', 'premium', 'nasi'],
      created_at: new Date('2024-02-01'),
      updated_at: new Date('2024-02-01'),
    },
    {
      user_id: mayaUser.id,
      product_master_id: gula.id,
      name: 'Gula Pasir 1kg',
      sku: 'MAYA-GULA-001',
      barcode: '8998866100135',
      description: 'Gula pasir putih 1kg',
      unit: 'pack',
      cost_price: 10000,
      selling_price: 12000,
      current_stock: 15,
      minimum_stock: 5,
      is_active: true,
      search_tags: ['gula', 'pasir', 'manis'],
      created_at: new Date('2024-02-01'),
      updated_at: new Date('2024-02-01'),
    },

    // Joko's Warung Sejahtera products
    {
      user_id: jokoUser.id,
      product_master_id: mieSedap.id,
      name: 'Mie Sedap Goreng',
      sku: 'JOKO-SEDAP-001',
      barcode: '8998866100050',
      description: 'Mie instan goreng rasa ayam',
      unit: 'pcs',
      cost_price: 2700,
      selling_price: 3200,
      current_stock: 40,
      minimum_stock: 12,
      is_active: true,
      search_tags: ['mie sedap', 'goreng', 'mie'],
      created_at: new Date('2024-01-20'),
      updated_at: new Date('2024-01-20'),
    },
    {
      user_id: jokoUser.id,
      product_master_id: rokokMarlboro.id,
      name: 'Rokok Marlboro Red 20',
      sku: 'JOKO-MARL-001',
      barcode: '8998866100180',
      description: 'Rokok filter Marlboro Red 20 batang',
      unit: 'pack',
      cost_price: 28000,
      selling_price: 32000,
      current_stock: 6,
      minimum_stock: 2,
      is_active: true,
      search_tags: ['rokok', 'marlboro', 'red'],
      created_at: new Date('2024-01-20'),
      updated_at: new Date('2024-01-20'),
    },
    {
      user_id: jokoUser.id,
      product_master_id: minyak.id,
      name: 'Minyak Goreng 2L',
      sku: 'JOKO-MINYAK-001',
      barcode: '8998866100142',
      description: 'Minyak goreng Bimoli 2 liter',
      unit: 'botol',
      cost_price: 22000,
      selling_price: 25000,
      current_stock: 8,
      minimum_stock: 3,
      is_active: true,
      search_tags: ['minyak', 'goreng', 'bimoli'],
      created_at: new Date('2024-01-20'),
      updated_at: new Date('2024-01-20'),
    },
    {
      user_id: jokoUser.id,
      product_master_id: kecap.id,
      name: 'Kecap Manis 600ml',
      sku: 'JOKO-KECAP-001',
      barcode: '8998866100159',
      description: 'Kecap manis Bango 600ml',
      unit: 'botol',
      cost_price: 12000,
      selling_price: 15000,
      current_stock: 12,
      minimum_stock: 4,
      is_active: true,
      search_tags: ['kecap', 'manis', 'bango'],
      created_at: new Date('2024-01-20'),
      updated_at: new Date('2024-01-20'),
    },

    // Sari's Minimarket Maju products
    {
      user_id: sariUser.id,
      product_master_id: sprite.id,
      name: 'Sprite 330ml',
      sku: 'SARI-SPRITE-001',
      barcode: '8998866100111',
      description: 'Minuman soda Sprite 330ml',
      unit: 'kaleng',
      cost_price: 6500,
      selling_price: 8000,
      current_stock: 35,
      minimum_stock: 15,
      is_active: true,
      search_tags: ['sprite', 'soda', 'lemon'],
      created_at: new Date('2024-03-10'),
      updated_at: new Date('2024-03-10'),
    },
    {
      user_id: sariUser.id,
      product_master_id: telur.id,
      name: 'Telur Ayam 1kg',
      sku: 'SARI-TELUR-001',
      barcode: '8998866100173',
      description: 'Telur ayam negeri 1kg',
      unit: 'kg',
      cost_price: 25000,
      selling_price: 28000,
      current_stock: 10,
      minimum_stock: 3,
      is_active: true,
      search_tags: ['telur', 'ayam', 'protein'],
      created_at: new Date('2024-03-10'),
      updated_at: new Date('2024-03-10'),
    },
    {
      user_id: sariUser.id,
      product_master_id: sambal.id,
      name: 'Sambal ABC 340ml',
      sku: 'SARI-SAMBAL-001',
      barcode: '8998866100166',
      description: 'Sambal ABC pedas 340ml',
      unit: 'botol',
      cost_price: 10000,
      selling_price: 12000,
      current_stock: 18,
      minimum_stock: 6,
      is_active: true,
      search_tags: ['sambal', 'abc', 'pedas'],
      created_at: new Date('2024-03-10'),
      updated_at: new Date('2024-03-10'),
    },
    {
      user_id: sariUser.id,
      product_master_id: pepsodent.id,
      name: 'Pepsodent 190g',
      sku: 'SARI-PEPSO-001',
      barcode: '8998866100197',
      description: 'Pasta gigi Pepsodent 190g',
      unit: 'pcs',
      cost_price: 7000,
      selling_price: 8500,
      current_stock: 25,
      minimum_stock: 8,
      is_active: true,
      search_tags: ['pepsodent', 'odol', 'gigi'],
      created_at: new Date('2024-03-10'),
      updated_at: new Date('2024-03-10'),
    },

    // Agus's Warung Makmur products
    {
      user_id: agusUser.id,
      product_master_id: rinso.id,
      name: 'Rinso 800g',
      sku: 'AGUS-RINSO-001',
      barcode: '8998866100203',
      description: 'Deterjen Rinso 800g',
      unit: 'pack',
      cost_price: 15000,
      selling_price: 18000,
      current_stock: 20,
      minimum_stock: 7,
      is_active: true,
      search_tags: ['rinso', 'deterjen', 'cuci'],
      created_at: new Date('2024-01-05'),
      updated_at: new Date('2024-01-05'),
    },
    {
      user_id: agusUser.id,
      product_master_id: roma.id,
      name: 'Biskuit Roma 135g',
      sku: 'AGUS-ROMA-001',
      barcode: '8998866100210',
      description: 'Biskuit Roma 135g',
      unit: 'pack',
      cost_price: 2800,
      selling_price: 3500,
      current_stock: 50,
      minimum_stock: 15,
      is_active: true,
      search_tags: ['roma', 'biskuit', 'snack'],
      created_at: new Date('2024-01-05'),
      updated_at: new Date('2024-01-05'),
    },
    {
      user_id: agusUser.id,
      product_master_id: chitato.id,
      name: 'Chitato 85g',
      sku: 'AGUS-CHITA-001',
      barcode: '8998866100227',
      description: 'Keripik kentang Chitato 85g',
      unit: 'pack',
      cost_price: 10000,
      selling_price: 12000,
      current_stock: 30,
      minimum_stock: 10,
      is_active: true,
      search_tags: ['chitato', 'keripik', 'kentang'],
      created_at: new Date('2024-01-05'),
      updated_at: new Date('2024-01-05'),
    },
    {
      user_id: agusUser.id,
      product_master_id: kopi.id,
      name: 'Kopi Kapal Api 200g',
      sku: 'AGUS-KOPI-001',
      barcode: '8998866100234',
      description: 'Kopi Kapal Api 200g',
      unit: 'pack',
      cost_price: 12000,
      selling_price: 15000,
      current_stock: 15,
      minimum_stock: 5,
      is_active: true,
      search_tags: ['kopi', 'kapal api', 'minuman'],
      created_at: new Date('2024-01-05'),
      updated_at: new Date('2024-01-05'),
    },
  ]);
}
