import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('product_master').del();

  // Inserts seed entries
  await knex('product_master').insert([
    {
      name: 'Indomie Goreng',
      brand: 'Indomie',
      category: 'Mie Instan',
      common_barcodes: ['8998866100012', '8998866100029'],
      common_units: 'pcs',
      search_tags: ['indomie', 'goreng', 'mie', 'instan', 'makanan'],
      popularity_score: 95,
      suggested_selling_price: 3500,
      description: 'Mie instan goreng rasa ayam bawang',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Indomie Kuah Ayam Bawang',
      brand: 'Indomie',
      category: 'Mie Instan',
      common_barcodes: ['8998866100036', '8998866100043'],
      common_units: 'pcs',
      search_tags: ['indomie', 'kuah', 'ayam', 'bawang', 'mie', 'instan'],
      popularity_score: 90,
      suggested_selling_price: 3000,
      description: 'Mie instan kuah rasa ayam bawang',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Mie Sedap Goreng',
      brand: 'Mie Sedap',
      category: 'Mie Instan',
      common_barcodes: ['8998866100050', '8998866100067'],
      common_units: 'pcs',
      search_tags: ['mie sedap', 'goreng', 'mie', 'instan'],
      popularity_score: 85,
      suggested_selling_price: 3200,
      description: 'Mie instan goreng rasa ayam',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Rokok Sampoerna Mild 16',
      brand: 'Sampoerna',
      category: 'Rokok',
      common_barcodes: ['8998866100074'],
      common_units: 'pack',
      search_tags: ['rokok', 'sampoerna', 'mild', 'filter'],
      popularity_score: 80,
      suggested_selling_price: 25000,
      description: 'Rokok filter mild 16 batang',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Rokok Djarum Super 12',
      brand: 'Djarum',
      category: 'Rokok',
      common_barcodes: ['8998866100081'],
      common_units: 'pack',
      search_tags: ['rokok', 'djarum', 'super', 'kretek'],
      popularity_score: 75,
      suggested_selling_price: 22000,
      description: 'Rokok kretek super 12 batang',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Aqua 600ml',
      brand: 'Aqua',
      category: 'Minuman',
      common_barcodes: ['8998866100098'],
      common_units: 'botol',
      search_tags: ['aqua', 'air', 'mineral', 'botol'],
      popularity_score: 100,
      suggested_selling_price: 3000,
      description: 'Air mineral dalam botol 600ml',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Coca Cola 330ml',
      brand: 'Coca Cola',
      category: 'Minuman',
      common_barcodes: ['8998866100104'],
      common_units: 'kaleng',
      search_tags: ['coca cola', 'cola', 'soda', 'minuman'],
      popularity_score: 85,
      suggested_selling_price: 8000,
      description: 'Minuman soda Coca Cola 330ml',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Sprite 330ml',
      brand: 'Sprite',
      category: 'Minuman',
      common_barcodes: ['8998866100111'],
      common_units: 'kaleng',
      search_tags: ['sprite', 'soda', 'minuman', 'lemon'],
      popularity_score: 80,
      suggested_selling_price: 8000,
      description: 'Minuman soda Sprite 330ml',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Beras Premium 5kg',
      brand: 'Beras Premium',
      category: 'Sembako',
      common_barcodes: ['8998866100128'],
      common_units: 'karung',
      search_tags: ['beras', 'premium', 'nasi', 'makanan'],
      popularity_score: 90,
      suggested_selling_price: 65000,
      description: 'Beras premium putih 5kg',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Gula Pasir 1kg',
      brand: 'Gula Pasir',
      category: 'Sembako',
      common_barcodes: ['8998866100135'],
      common_units: 'pack',
      search_tags: ['gula', 'pasir', 'manis', 'makanan'],
      popularity_score: 85,
      suggested_selling_price: 12000,
      description: 'Gula pasir putih 1kg',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Minyak Goreng 2L',
      brand: 'Bimoli',
      category: 'Sembako',
      common_barcodes: ['8998866100142'],
      common_units: 'botol',
      search_tags: ['minyak', 'goreng', 'bimoli', 'masak'],
      popularity_score: 88,
      suggested_selling_price: 25000,
      description: 'Minyak goreng Bimoli 2 liter',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Kecap Manis 600ml',
      brand: 'Bango',
      category: 'Bumbu',
      common_barcodes: ['8998866100159'],
      common_units: 'botol',
      search_tags: ['kecap', 'manis', 'bango', 'bumbu'],
      popularity_score: 82,
      suggested_selling_price: 15000,
      description: 'Kecap manis Bango 600ml',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Sambal ABC 340ml',
      brand: 'ABC',
      category: 'Bumbu',
      common_barcodes: ['8998866100166'],
      common_units: 'botol',
      search_tags: ['sambal', 'abc', 'pedas', 'bumbu'],
      popularity_score: 78,
      suggested_selling_price: 12000,
      description: 'Sambal ABC pedas 340ml',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Telur Ayam 1kg',
      brand: 'Telur Ayam',
      category: 'Sembako',
      common_barcodes: ['8998866100173'],
      common_units: 'kg',
      search_tags: ['telur', 'ayam', 'protein', 'makanan'],
      popularity_score: 92,
      suggested_selling_price: 28000,
      description: 'Telur ayam negeri 1kg',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Rokok Marlboro Red 20',
      brand: 'Marlboro',
      category: 'Rokok',
      common_barcodes: ['8998866100180'],
      common_units: 'pack',
      search_tags: ['rokok', 'marlboro', 'red', 'filter'],
      popularity_score: 70,
      suggested_selling_price: 32000,
      description: 'Rokok filter Marlboro Red 20 batang',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Pepsodent 190g',
      brand: 'Pepsodent',
      category: 'Kebersihan',
      common_barcodes: ['8998866100197'],
      common_units: 'pcs',
      search_tags: ['pepsodent', 'odol', 'sikat', 'gigi'],
      popularity_score: 75,
      suggested_selling_price: 8500,
      description: 'Pasta gigi Pepsodent 190g',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Rinso 800g',
      brand: 'Rinso',
      category: 'Kebersihan',
      common_barcodes: ['8998866100203'],
      common_units: 'pack',
      search_tags: ['rinso', 'deterjen', 'cuci', 'baju'],
      popularity_score: 80,
      suggested_selling_price: 18000,
      description: 'Deterjen Rinso 800g',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Biskuit Roma 135g',
      brand: 'Roma',
      category: 'Snack',
      common_barcodes: ['8998866100210'],
      common_units: 'pack',
      search_tags: ['roma', 'biskuit', 'snack', 'makanan'],
      popularity_score: 85,
      suggested_selling_price: 3500,
      description: 'Biskuit Roma 135g',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Chitato 85g',
      brand: 'Chitato',
      category: 'Snack',
      common_barcodes: ['8998866100227'],
      common_units: 'pack',
      search_tags: ['chitato', 'keripik', 'snack', 'kentang'],
      popularity_score: 88,
      suggested_selling_price: 12000,
      description: 'Keripik kentang Chitato 85g',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      name: 'Kopi Kapal Api 200g',
      brand: 'Kapal Api',
      category: 'Minuman',
      common_barcodes: ['8998866100234'],
      common_units: 'pack',
      search_tags: ['kopi', 'kapal api', 'minuman', 'sachet'],
      popularity_score: 90,
      suggested_selling_price: 15000,
      description: 'Kopi Kapal Api 200g',
      is_verified: true,
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
  ]);
}
